### ISSUE TITLE
cuDNN error: CUDNN_STATUS_EXECUTION_FAILEDUnable to run sorry. could you release the steps from initial environment to running the code?

### ISSUE THREAD

**Issue by qinxiaole** [MASILab/tumor-cifar#2]
I still met this problem:     "cuDNN error: CUDNN_STATUS_EXECUTION_FAILED. "
Unable to fix it.
Could you release the steps from initial environment to running the code?
Thanks!

More details of our environment:                   
cudatoolkit               9.0                          
numpy                     1.19.5                 
pandas                    1.1.5                   
python                    3.6.13               
pytorch                   1.1.0           py3.6_cuda90_cudnn7_1    pytorch
scipy                     1.5.4                  
tensorflow                1.9.0                   
torchvision               0.9.1                 
tqdm                      4.60.0

**Comment by RiqiangGao** [comment]
Thank you for your interest. I was running the experiments on cuda10. I think this might be a problem as you're running on 9.0.
