### ISSUE TITLE
"T-LSTM"and "TimeLSTM" are missing in functional code

### ISSUE THREAD

**Issue by qinxiaole** [MASILab/tumor-cifar#4]
Hello authors!

 Thanks for sharing the implementation details. I started running your codes, but "T-LSTM"and "TimeLSTM" are missing in the
functional code

Can you please provide the code of "T-LSTM"and "TimeLSTM" ?

Thank you very much!
![image](https://user-images.githubusercontent.com/49808487/122640612-1de4c000-d133-11eb-8180-d8591add88cb.png)

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
